version: "3"

services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: Eris2020!
    volumes:
      - ./scripts/init.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - "5432:5432"